# Generated by Django 5.1.7 on 2025-04-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the college', max_length=100, unique=True, verbose_name='College Name')),
                ('code', models.CharField(help_text='Short unique code for the college (e.g., SCI for Science)', max_length=10, unique=True, verbose_name='College Code')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the college', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(help_text='Official name of the department', max_length=100, unique=True, verbose_name='Department Name')),
                ('department_code', models.CharField(help_text='Short unique code for the department (e.g., DCS for Computer Science)', max_length=10, unique=True, verbose_name='Department Code')),
                ('details', models.TextField(blank=True, help_text='Detailed description of the department', null=True, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update', verbose_name='Updated At')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.college')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='Official name of the course', max_length=100, unique=True, verbose_name='Course Name')),
                ('course_code', models.CharField(help_text='Short unique code for the course (e.g., CS101 for Introduction to Computer Science)', max_length=10, unique=True, verbose_name='Course Code')),
                ('details', models.TextField(blank=True, help_text='Detailed description of the course', null=True, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update', verbose_name='Updated At')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['course_name'],
            },
        ),
    ] 