# Generated by Django 5.1.7 on 2025-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the faculty', max_length=100, unique=True, verbose_name='Faculty Name')),
                ('code', models.CharField(help_text='Short unique code for the faculty (e.g., SCI for Science)', max_length=10, unique=True, verbose_name='Faculty Code')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the faculty', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'code'), name='unique_faculty_identifier')],
            },
        ),
    ]
