# Generated by Django 5.1.7 on 2025-03-17 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(help_text='Official name of the department', max_length=100, unique=True, verbose_name='Department Name')),
                ('department_code', models.CharField(help_text='Short unique code for the department (e.g., DCS for Computer Science)', max_length=10, unique=True, verbose_name='Department Code')),
                ('details', models.TextField(blank=True, help_text='Detailed description of the department', null=True, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update', verbose_name='Updated At')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.faculty')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['department_name'],
                'constraints': [models.UniqueConstraint(fields=('department_name', 'department_code'), name='unique_department_identifier')],
            },
        ),
    ]
