# Generated by Django 5.1.7 on 2025-03-21 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='Official name of the course', max_length=100, unique=True, verbose_name='Course Name')),
                ('course_code', models.CharField(help_text='Short unique code for the course (e.g., CS101 for Introduction to Computer Science)', max_length=10, unique=True, verbose_name='Course Code')),
                ('details', models.TextField(blank=True, help_text='Detailed description of the course', null=True, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update', verbose_name='Updated At')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['course_name'],
                'constraints': [models.UniqueConstraint(fields=('course_name', 'course_code'), name='unique_course_identifier')],
            },
        ),
    ]
