# Generated by Django 5.2 on 2025-04-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_issue'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='college',
            constraint=models.UniqueConstraint(fields=('name', 'code'), name='unique_college_identifier'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_name', 'course_code'), name='unique_course_identifier'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('department_name',), name='unique_department_identifier'),
        ),
    ]
