# Generated by Django 5.1.7 on 2025-03-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_department_identifier',
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('department_name',), name='unique_department_identifier'),
        ),
    ]
