# Generated by Django 5.1.7 on 2025-03-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_department_unique_department_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('COCIS', 'College of Computing and Information Sciences'), ('CEDAT', 'College of Engineering, Design, Art and Technology'), ('LAW', 'School of Law'), ('CAES', 'College of Agricultural and Environmental Sciences'), ('CHUSS', 'College of Humanities and Social Sciences'), ('CONAS', 'College of Natural Sciences'), ('EDUC', 'School of Education'), ('CHS', 'College of Health Sciences'), ('COVAB', 'College of Veterinary Medicine, Animal Resources and Bio-security'), ('COBAMS', 'College of Business and Management Sciences')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
            },
        ),
    ]
