# Generated by Django 5.1.7 on 2025-04-03 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_college'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['code'], 'verbose_name': 'College', 'verbose_name_plural': 'Colleges'},
        ),
    ]
