# Generated by Django 5.1.7 on 2025-04-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_issue_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('Missing Marks', 'Missing Marks'), ('Appeals', 'Appeals'), ('Corrections', 'Corrections')], max_length=50),
        ),
    ]
