# Generated by Django 5.1.7 on 2025-04-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_notification_message_alter_notification_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='lecturer',
        ),
        migrations.DeleteModel(
            name='IssueAssignmentHistory',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
