# Generated by Django 5.2 on 2025-04-09 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_college_unique_college_identifier_and_more'),
        ('users', '0002_alter_user_options_remove_user_is_admin_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod', to='api.department'),
        ),
    ]
